#include "CsvReader.h"
#include "SalesService.h"
#include "RevenueService.h"
#include <iostream>
#include <thread>


using namespace std;

int main(){
    CsvReader csvReader;
    SalesService salesService;
    RevenueService revenueService;

    csvReader.load("world_car_sales_1m.csv");   

    cout << "------------------------------------------" << endl;
    
    cout << "1. Audi Sales in China (2025): " << salesService.countSales(csvReader.headerMap, csvReader.flatIndex
    , "Audi", "China", "2025") << "\n";
    
    cout << "------------------------------------------" << endl;
    
    cout << "2. Total revenue generated by BMW in 2025: " << fixed << setprecision(2) << revenueService.calculateTotalRevenue(csvReader, "BMW", "2025") << "\n";
    cout << "------------------------------------------" << endl;
    vector<CountryRevenue> report = revenueService.getRevenueByCountry(csvReader, "BMW", "Europe");

    cout << "3. BMW Revenue Distribution (Europe) \n";
    cout << left << setw(20) << "Country" << "Revenue (USD)" << endl;
    cout << "------------------------------------------" << endl;

    cout << fixed << setprecision(2);
    for (const auto& item : report) {
        cout << left << setw(20) << item.country 
             << "$" << item.revenue << endl;
    }

    return 0;
}
